//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFP.Gerencia.Domain.ValueObjects.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesDomain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesDomain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoFP.Gerencia.Domain.ValueObjects.Resource.MessagesDomain", typeof(MessagesDomain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo CEP.
        /// </summary>
        public static string AddressCEPInvalid {
            get {
                return ResourceManager.GetString("AddressCEPInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O complemento deve possuir entre 2 à 50 caracteres.
        /// </summary>
        public static string AddressComplementInvalid {
            get {
                return ResourceManager.GetString("AddressComplementInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha informando seu bairro.
        /// </summary>
        public static string AddressNeighborhoodInvalid {
            get {
                return ResourceManager.GetString("AddressNeighborhoodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o número referente ao seu endereço.
        /// </summary>
        public static string AddressNumberInvalid {
            get {
                return ResourceManager.GetString("AddressNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um ponto de referência.
        /// </summary>
        public static string AddressPointReferenceInvalid {
            get {
                return ResourceManager.GetString("AddressPointReferenceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o logradouro.
        /// </summary>
        public static string AddressStreetInvalid {
            get {
                return ResourceManager.GetString("AddressStreetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome permitido entre 1 à 50 carateres.
        /// </summary>
        public static string CarNameInvalid {
            get {
                return ResourceManager.GetString("CarNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione as categorias de peças que a marca trabalha.
        /// </summary>
        public static string CategoriesPieceSelectedInvalid {
            get {
                return ResourceManager.GetString("CategoriesPieceSelectedInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de categoria de peça deve ser maior que zero.
        /// </summary>
        public static string CategoryPieceIdInvalid {
            get {
                return ResourceManager.GetString("CategoryPieceIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha a categoria de peça.
        /// </summary>
        public static string CategoryPieceInvalid {
            get {
                return ResourceManager.GetString("CategoryPieceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o município referência ao endereço.
        /// </summary>
        public static string CodeCityToAddressGreaterThanZero {
            get {
                return ResourceManager.GetString("CodeCityToAddressGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de cidade referência à estado deve ser maior que zero.
        /// </summary>
        public static string CodeCityToStateGreaterThanZero1 {
            get {
                return ResourceManager.GetString("CodeCityToStateGreaterThanZero1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os códigos: traseiro e dianteiro não podem ser vazios simultaneamente.
        /// </summary>
        public static string CodeFrontAndBackEmpty {
            get {
                return ResourceManager.GetString("CodeFrontAndBackEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os códigos: traseiro e dianteiro não podem ser informados simultaneamente.
        /// </summary>
        public static string CodeFrontAndBackNotEmpty {
            get {
                return ResourceManager.GetString("CodeFrontAndBackNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código referência de status de peça (nova ou recondicionada) deve ser maior que zero.
        /// </summary>
        public static string CodeInvalidStatusToPiece {
            get {
                return ResourceManager.GetString("CodeInvalidStatusToPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de pessoa jurídica deve ser maior que zero.
        /// </summary>
        public static string CodePersonJuridicalGreaterThanZero {
            get {
                return ResourceManager.GetString("CodePersonJuridicalGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código referência de marca para peça deve ser maior que zero.
        /// </summary>
        public static string CodeProductMarkGreaterThanZero {
            get {
                return ResourceManager.GetString("CodeProductMarkGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código referência de fornecedor para peça deve ser maior que zero.
        /// </summary>
        public static string CodeProviderToProductGreaterThanZero {
            get {
                return ResourceManager.GetString("CodeProviderToProductGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o nome do estado corretamente.
        /// </summary>
        public static string DescriptionStateInvalid {
            get {
                return ResourceManager.GetString("DescriptionStateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de CNPJ inválido.
        /// </summary>
        public static string DocumentCnpjInvalid {
            get {
                return ResourceManager.GetString("DocumentCnpjInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de endereço deve ser maior que zero.
        /// </summary>
        public static string InvalidAddressId {
            get {
                return ResourceManager.GetString("InvalidAddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código da montadora deve ser maior que zero..
        /// </summary>
        public static string InvalidAutomobileManufacturerID {
            get {
                return ResourceManager.GetString("InvalidAutomobileManufacturerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano de modelo do carro está fora do intervalo {0} à {1}.
        /// </summary>
        public static string InvalidCarModelYearInterval {
            get {
                return ResourceManager.GetString("InvalidCarModelYearInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código para cidade deve ser maior que zero.
        /// </summary>
        public static string InvalidCityId {
            get {
                return ResourceManager.GetString("InvalidCityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de cliente deve ser maior que zero.
        /// </summary>
        public static string InvalidClientId {
            get {
                return ResourceManager.GetString("InvalidClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de referência a carro deve ser maior que zero.
        /// </summary>
        public static string InvalidCodeCarGreaterThanZero {
            get {
                return ResourceManager.GetString("InvalidCodeCarGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de referência ao modelo do carro deve ser maior que zero.
        /// </summary>
        public static string InvalidCodeCarModelGreaterThanZero {
            get {
                return ResourceManager.GetString("InvalidCodeCarModelGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código referência a peça na galeria de imagens deve ser maior que zero.
        /// </summary>
        public static string InvalidCodeGaleryToPieceGreaterThanZero {
            get {
                return ResourceManager.GetString("InvalidCodeGaleryToPieceGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de linha de peça paralela deve ser maior que zero.
        /// </summary>
        public static string InvalidCodeLinePecaGreaterThanZero {
            get {
                return ResourceManager.GetString("InvalidCodeLinePecaGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDD inválido, deve haver apenas 2 números.
        /// </summary>
        public static string InvalidDDDTelephone {
            get {
                return ResourceManager.GetString("InvalidDDDTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de email deve ser maior que zero.
        /// </summary>
        public static string InvalidEmailId {
            get {
                return ResourceManager.GetString("InvalidEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código para item em galeria de produto deve ser maior que zero.
        /// </summary>
        public static string InvalidGaleryId {
            get {
                return ResourceManager.GetString("InvalidGaleryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da montadoura deve ter de 2 à 50 caracteres, para mais, fale com o administrador.
        /// </summary>
        public static string InvalidManufacturerDescription {
            get {
                return ResourceManager.GetString("InvalidManufacturerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da montadora para o carro deve ser mair que zero.
        /// </summary>
        public static string InvalidManufacturerToCarCodeGreaterThanZero {
            get {
                return ResourceManager.GetString("InvalidManufacturerToCarCodeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da marca de peças deve ser maior que zero.
        /// </summary>
        public static string InvalidMarkToCarCodeGreaterThanZero {
            get {
                return ResourceManager.GetString("InvalidMarkToCarCodeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de pessoa deve ser maior que zero.
        /// </summary>
        public static string InvalidPersonId {
            get {
                return ResourceManager.GetString("InvalidPersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de peça deve ser maior que zero.
        /// </summary>
        public static string InvalidPieceId {
            get {
                return ResourceManager.GetString("InvalidPieceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código para posição de peça deve ser maior que zero.
        /// </summary>
        public static string InvalidPiecePositionId {
            get {
                return ResourceManager.GetString("InvalidPiecePositionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de fornecedor deve ser maior que zero.
        /// </summary>
        public static string InvalidProviderId {
            get {
                return ResourceManager.GetString("InvalidProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código para estado deve ser maior que zero.
        /// </summary>
        public static string InvalidStateId {
            get {
                return ResourceManager.GetString("InvalidStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de telefone inválido.
        /// </summary>
        public static string InvalidTelephone {
            get {
                return ResourceManager.GetString("InvalidTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de telefone deve ser maior que zero.
        /// </summary>
        public static string InvalidTelephoneId {
            get {
                return ResourceManager.GetString("InvalidTelephoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de pessoa deve ser pessoa física ou juridica, valor inválido.
        /// </summary>
        public static string InvalidTypePerson {
            get {
                return ResourceManager.GetString("InvalidTypePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF de estado inválida.
        /// </summary>
        public static string InvalidUf {
            get {
                return ResourceManager.GetString("InvalidUf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da marca deve ter de 2 à 50 caracteres, para mais, fale com o administrador..
        /// </summary>
        public static string MarkInvalidCaractere {
            get {
                return ResourceManager.GetString("MarkInvalidCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome fantasia não pode estar em branco.
        /// </summary>
        public static string NameFantasyEmpty {
            get {
                return ResourceManager.GetString("NameFantasyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome inválido.
        /// </summary>
        public static string NamePerson {
            get {
                return ResourceManager.GetString("NamePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por gentileza, verifique o número de CPF.
        /// </summary>
        public static string NumeroDeCpfInvalido {
            get {
                return ResourceManager.GetString("NumeroDeCpfInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de linha paralela informado não é um valor válido.
        /// </summary>
        public static string ParallelLineNumberInvalid {
            get {
                return ResourceManager.GetString("ParallelLineNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de linha paralela deve ser informado quando a peça não é original.
        /// </summary>
        public static string ParallelLineNumberNotInformation {
            get {
                return ResourceManager.GetString("ParallelLineNumberNotInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode estar em branco.
        /// </summary>
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o código do distribuidor.
        /// </summary>
        public static string ProductCodeDistributor {
            get {
                return ResourceManager.GetString("ProductCodeDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha a descrição do produto.
        /// </summary>
        public static string ProductDescriptionInvalid {
            get {
                return ResourceManager.GetString("ProductDescriptionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe as medidas da peça.
        /// </summary>
        public static string ProductMeasureInvalid {
            get {
                return ResourceManager.GetString("ProductMeasureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do produto é obrigatório.
        /// </summary>
        public static string ProductNameInvalid {
            get {
                return ResourceManager.GetString("ProductNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linha de peça paralela não se aplica em peças originais.
        /// </summary>
        public static string ProductOriginalNotLine {
            get {
                return ResourceManager.GetString("ProductOriginalNotLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor da peça deve ser maior que zero.
        /// </summary>
        public static string ProductPriceInvalid {
            get {
                return ResourceManager.GetString("ProductPriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramal telefônico inválido.
        /// </summary>
        public static string RamalTelephoneInvalid {
            get {
                return ResourceManager.GetString("RamalTelephoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão social não pode estar em branco.
        /// </summary>
        public static string RazaoSocialEmpty {
            get {
                return ResourceManager.GetString("RazaoSocialEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome inválido.
        /// </summary>
        public static string SobrenomePerson {
            get {
                return ResourceManager.GetString("SobrenomePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone deve possuir 11 caracteres para celular e 10 para fixo, incluindo DDD..
        /// </summary>
        public static string TelephoneLength {
            get {
                return ResourceManager.GetString("TelephoneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de telefone incorreto.
        /// </summary>
        public static string TelephoneRelationshipId {
            get {
                return ResourceManager.GetString("TelephoneRelationshipId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ano informado não é válido.
        /// </summary>
        public static string YearInvalid {
            get {
                return ResourceManager.GetString("YearInvalid", resourceCulture);
            }
        }
    }
}
