//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFP.Gerencia.Application.ValueObjects.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesSuccess {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesSuccess() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoFP.Gerencia.Application.ValueObjects.Resource.MessagesSuccess", typeof(MessagesSuccess).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montadora {0} registrada com sucesso.
        /// </summary>
        public static string AutomakerRegistred {
            get {
                return ResourceManager.GetString("AutomakerRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montadora removida com sucesso.
        /// </summary>
        public static string AutomakerRemoved {
            get {
                return ResourceManager.GetString("AutomakerRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montadora {0} atualizada com sucesso.
        /// </summary>
        public static string AutomakerUpdated {
            get {
                return ResourceManager.GetString("AutomakerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria removida com sucesso.
        /// </summary>
        public static string CategoriaPieceRemoved {
            get {
                return ResourceManager.GetString("CategoriaPieceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria {0} registrada com sucesso.
        /// </summary>
        public static string CategoryPieceRegistred {
            get {
                return ResourceManager.GetString("CategoryPieceRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria {0} atualizada com sucesso.
        /// </summary>
        public static string CategoryPieceUpdated {
            get {
                return ResourceManager.GetString("CategoryPieceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente {0} registrado com sucesso.
        /// </summary>
        public static string ClientRegistred {
            get {
                return ResourceManager.GetString("ClientRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca {0} registrada com sucesso.
        /// </summary>
        public static string MakerRegistred {
            get {
                return ResourceManager.GetString("MakerRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca removida com sucesso.
        /// </summary>
        public static string MakerRemoved {
            get {
                return ResourceManager.GetString("MakerRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca {0} atualizada com sucesso.
        /// </summary>
        public static string MakerUpdated {
            get {
                return ResourceManager.GetString("MakerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor {0} registrado com sucesso.
        /// </summary>
        public static string ProviderRegistred {
            get {
                return ResourceManager.GetString("ProviderRegistred", resourceCulture);
            }
        }
    }
}
